export default {
    mongoURI:'mongodb+srv://aneesrehman:anees684@cluster0.knajhqm.mongodb.net/?retryWrites=true&w=majority',
    suits:[
            "Spades", 
            "Diamonds",
            "Club",
            "Heart"
        ],
    ranks:[
        "Ace",
        "2",
        "3",
        "4",
        "5",
        "6",
        "7",
        "8",
        "9",
        "10",
        "Jack",
        "Queen",
        "King",
      ]
}